trigger: 'none' # will disable CI builds entirely

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: AzureKeyVault@2
  displayName: 'Get Secrets from key vault'
  inputs:
    azureSubscription: 'Free Trial (958de31c-6eda-4f41-a1b0-755df90f75f8)'
    KeyVaultName: AbhayEgonKeyVault
    SecretsFilter: "*"
- task: CmdLine@2
  inputs:
    script: |
      echo $(DemoSecret) > secret.txt
      cat secret.txt

- task: CopyFiles@2
  displayName: Copy Secrets File
  inputs:
    Contents: 'secret.txt'
    TargetFolder: '$(Build.ArtificatStagingDirectory)'